"""
Nessus CLI "Bug Report Archive" Tests

Test the nessuscli bug-report-generator command and flags.

:copyright: Tenable Network Security, 2017
:date: April 24, 2023
:author: @pellsworth, @vsoni.ctr, @krpatel.ctr, @mdabra
"""
import os

import pytest

from catium.helpers.sleep_lib import sleep
from catium.lib import const
from catium.lib.ssh.ssh import SSH
from nessus.helpers.nessuscli import bug_report
from nessus.helpers.nessuscli.helper import get_command, path_join, get_nessus_cli, get_nessus_log_dir, \
    get_nessus_com_dir
from nessus.lib.config.environment_variables import NESSUS_PLATFORM
from nessus.lib.const.constants import NessusCli
from nessus.lib.const.constants import OperatingSystems


sudo = NESSUS_PLATFORM in [OperatingSystems.MAC, OperatingSystems.MAC_OS]


class TestNessusDebugGenerator:
    """ Test nessuscli bug-report-generator commands """

    @staticmethod
    def generate_bug_report_and_extract_files():
        """
        Generates bug report tar file and extracts the same to "bug_report" folder.
        """
        bug_report.generate_quiet()
        archive_file_path = os.path.join(get_nessus_log_dir(), NessusCli.BugReportGenerator.ZIP_FILE_NAME)

        with SSH() as ssh:
            assert ssh.path_exist(archive_file_path), "Bug report tar file did not generated."

            ssh.execute("{} {}".format(get_command('unzip_files'), archive_file_path))

            assert ssh.path_exist(remote_path=NessusCli.BugReportGenerator.BUG_REPORT_FILES_DIR), \
                "Tar file for bug report did not extracted properly"

    @pytest.mark.nessus_manager
    @pytest.mark.nessus_expert
    @pytest.mark.nessus_pro
    @pytest.mark.skip(reason='NES-17105: fix will come later')
    def test_bug_report_archive(self):
        output = bug_report.generate_quiet()
        assert not output['stderr'], 'Error while executing bug report generator command'

    @pytest.mark.xray(test_key='NES-14841')
    @pytest.mark.parametrize('nessus_type', [
        pytest.param("Nessus Professional", marks=(pytest.mark.nessus_pro, pytest.mark.nessus_pro_mat)),
        pytest.param("Nessus Manager", marks=(pytest.mark.nessus_manager, pytest.mark.nessus_manager_mat))])
    @pytest.mark.parametrize('files_to_verify', [NessusCli.BugReportGenerator.BUG_REPORT_CERT_FILES,
                                                 NessusCli.BugReportGenerator.BUG_REPORT_ADDITIONAL_FILES])
    def test_bug_report_contains_required_files(self, nessus_type, files_to_verify):
        """
        NES-12004 : CLI automation for NES-11777
        Add cacert.pem, servercert.pem, license info, and ms_cert to the debug report (NES-11777)
        NES-13249 : [CLI-Automation] : Automate the new files added in bug-report-generator function
        NES-14841 : Execute bug-report-generator command and verify 3 new files in bug-report.

        Scenario Tested:
            [x] Verify cacert.pem and servercert.pem files  are
                getting generated by bug-report-generator command and they are non-empty.
            [x] Verify that product_summary.txt, .autoconfigure.json and cert_check.txt files are
                getting generated by bug-report-generator command and they are non-empty.
        """
        # Generating the bug report in quite mode
        bug_report.generate_quiet()

        # tar file path from directory.

        archive_file_path = os.path.join(get_nessus_log_dir(), NessusCli.BugReportGenerator.ZIP_FILE_NAME)

        with SSH() as ssh:
            # Verify bug report file is generated.
            assert ssh.path_exist(archive_file_path), "Bug report tar file did not generated."

            ssh.execute("{} {}".format(get_command('unzip_files'), archive_file_path))
            sleep(const.WAIT_SHORT, reason='waiting for extraction')
            # Verify the file is extracted properly or not.
            assert ssh.path_exist(remote_path=NessusCli.BugReportGenerator.BUG_REPORT_FILES_DIR), \
                "Tar file for bug report did not extracted properly"

            # Verify that all required files are present and non-empty.
            for file in files_to_verify:
                file_path = path_join(path_dir_list=[NessusCli.BugReportGenerator.BUG_REPORT_FILES_DIR, file])

                assert ssh.path_exist(remote_path=file_path) and int(ssh.execute(get_command(
                    "get_file_size").format(file_path))[0]) > 0, "{} file is not present or empty".format(file)

                replaced_path = file_path.replace("\\", "//") if \
                    NESSUS_PLATFORM in [OperatingSystems.MAC, OperatingSystems.MAC_OS] else file_path

                file_size_op = ssh.execute(get_command("get_file_size").format(replaced_path))[0]
                # replace te file size.
                replaced_file_size = file_size_op.split()[4] if \
                    NESSUS_PLATFORM in [OperatingSystems.MAC, OperatingSystems.MAC_OS] else file_size_op

                # Verify the file is present, and it's not empty at all.
                assert ssh.path_exist(remote_path=replaced_path), "{} file is not present".format(file)
                assert int(replaced_file_size) > 0, "{} File size is not empty or zero".format(file)

    @pytest.mark.xray(test_key='NES-14835')
    @pytest.mark.nessus_manager
    @pytest.mark.nessus_expert
    @pytest.mark.nessus_pro
    def test_verify_cert_check_related_information_in_bug_report(self):
        """
        NES-12904: CLI-Automation for NES-12391 : Verification of cacert.pem and servercert.pem in debug report, logs
        NES-14835: Verify cert_check file details.

        Scenario Tested:
            [x] Verify that newly added certcheck related debug log entries appear in bug report generator
                command's output.
            [x] Verify that certcheck.txt file contains required information to confirm servercert against cacert.
        """
        bug_report_output = bug_report.generate_quiet()

        archive_file_path = os.path.join(get_nessus_log_dir(), NessusCli.BugReportGenerator.ZIP_FILE_NAME)

        # Verify that newly added certcheck related debug log entries appear in bug report generator command's output.
        assert NessusCli.BugReportGenerator.CERT_CHECK_LOGS.issubset(set(bug_report_output['stdout'].split('\n'))), \
            "Certcheck related logs does not populated in bug report generator output."

        with SSH() as ssh:
            ssh.execute("{} {}".format(get_command('unzip_files'), archive_file_path))

            file_path = path_join(path_dir_list=[NessusCli.BugReportGenerator.BUG_REPORT_FILES_DIR, NessusCli.BugReportGenerator.CERT_CHECK])

            replaced_path = file_path.replace("\\", "//") if NESSUS_PLATFORM in [OperatingSystems.MAC,
                                                                                 OperatingSystems.MAC_OS] else file_path

            file_size_op = ssh.execute(get_command("get_file_size").format(replaced_path))[0]
            replaced_file_size = file_size_op.split()[4] if NESSUS_PLATFORM in [OperatingSystems.MAC,
                                                                                OperatingSystems.MAC_OS] else file_size_op

            # Verify that 'cert_check.txt' file generated via bug-report-generator function and is not empty.
            assert ssh.path_exist(replaced_path) and int(replaced_file_size) > 0, \
                "{} file is not present or empty".format(file_path)

            cert_check_file = ssh.read_from_file(path_join(path_dir_list=[NessusCli.BugReportGenerator.BUG_REPORT_FILES_DIR,
                                                                          NessusCli.BugReportGenerator.CERT_CHECK])).decode('utf-8')

            nessus_com_dir = get_nessus_com_dir()

            # Verify that cert_check.txt file contains required information to confirm servercert against cacert.
            assert NessusCli.ServerCertAndCaCert.CERT_CONFIRMED.format(nessus_com_dir, nessus_com_dir) in \
                   cert_check_file, "Required log is not present in 'cert_check.txt' file. cert_check.txt file " \
                                    "content is : {}".format(cert_check_file)

    @pytest.mark.xray(test_key='NES-15125')
    @pytest.mark.nessus_manager
    @pytest.mark.nessus_expert
    @pytest.mark.nessus_pro
    @pytest.mark.skip_rhel8
    def test_verify_auto_configure_file_contents(self):
        """
        NES-13249 : [CLI-Automation] : Automate the new files added in bug-report-generator function
        NES-15125 : Verify product_summary.txt file details.

        Scenario Tested:
            [x] Verify the information inside '.autoconfigure.json' generated via bug-report-generator
        """
        self.generate_bug_report_and_extract_files()

        with SSH() as ssh:

            autoconfigure_file_content = ssh.execute("{} {}".format(get_command('display_content'), path_join(
                path_dir_list=[NessusCli.BugReportGenerator.BUG_REPORT_FILES_DIR,
                               NessusCli.BugReportGenerator.AUTO_CONFIGURE])))

            assert autoconfigure_file_content[0] == NessusCli.BugReportGenerator.AUTO_CONFIGURE_JSON, \
                ".autoconfigure.json file's content is incorrect."

    @pytest.mark.xray(test_key='NES-14902')
    @pytest.mark.parametrize('nessus_type', [
        pytest.param("Nessus Professional", marks=pytest.mark.nessus_pro),
        pytest.param("Nessus Manager", marks=pytest.mark.nessus_manager)])
    def test_verify_product_summary_file_contents(self, nessus_type):
        """
        NES-13249 : [CLI-Automation] : Automate the new files added in bug-report-generator function
        NES-14902 : Verify .autoconfiguration.json file details.

        Scenario Tested:
            [x] Verify the information inside 'product_summary.txt' generated via bug-report-generator
        """
        self.generate_bug_report_and_extract_files()

        with SSH() as ssh:
            product_summary_file = ssh.execute("{} {}".format(get_command('display_content'), path_join(
                path_dir_list=[NessusCli.BugReportGenerator.BUG_REPORT_FILES_DIR,
                               NessusCli.BugReportGenerator.PRODUCT_SUMMARY])))

            # steps: Verify that all necessary information is present inside product summary file.
            if nessus_type == "Nessus Manager":
                assert [tag.split(":")[0].strip() for tag in product_summary_file if ":" in tag and tag !=
                        ""] == NessusCli.BugReportGenerator.PRODUCT_SUMMARY_TAGS_MANAGER, 'Product summery tags are incorrect.'
            else:
                assert [tag.split(":")[0].strip() for tag in product_summary_file if ":" in tag and tag !=
                        ""] == NessusCli.BugReportGenerator.PRODUCT_SUMMARY_TAGS_PRO, 'Product summary tags are incorrect.'

            # Verify product summery tags
            assert all([True for tag in product_summary_file if ":" in tag and "Features" not in tag and tag.split(
                ":")[1].strip() != ""]), "one or many product summary tags are empty."

            # Verify Nessus Type in product summary file.
            assert [tag.split(":")[1].strip() for tag in product_summary_file if "Name" in tag][0] == nessus_type, \
                "Product name is incorrect."

            output = ssh.execute("{} -v".format(get_nessus_cli()))[0]
            nessus_version = output[output.find(')') + 1:output.rfind('[')].strip(' ')

            # Verify Nessus Version in product summary file.
            assert [tag.split(":")[1].strip() for tag in product_summary_file if "Product" in tag][0] == \
                   nessus_version, "Product version is incorrect."
