# All markers that apply to the Core and Product frameworks should be defined here.
# If defining a product specific marker then please prefix it with the product's acronym.


[pytest]
addopts = -v -s -rs
          -p "catium.plugins.monkeypatch"
          -p "catium.plugins.fixtures"
          -p "catium.plugins.catium_jira"
          -p "catium.plugins.maxskip"  --max_skip_perc 100
          -p "catium.plugins.user_agent"
          -p "nessus.plugins.deployment"
          -p "nessus.plugins.xray_cloud.plugin"
;          --no-print-logs
          --show-capture=no

markers =
    # Common Markers
    agent: mark a test as part of the agent suite.
    controller: mark a test as part of the manager/controller.
    docker: mark a test a test that uses docker.
    extended_smoke: mark a test as part of the extended smoke test.
    integration: mark a test as part of the integration suite.
    io_onprem: mark test that is a known tenable.io onprem test
    io_onprem_install: mark test that is a known tenable.io onprem installation test
    long_running: mark a test as a long running test. These run in their own separate bamboo job.
    managed_scanner: mark a test as part of the managed scanner suite.
    plugins: mark a test as part of the plugins test suite.
    scanning: mark a test as a test that performs scanning against targets.
    scanning_deviation: mark test as a test that performs scanning time deviations.
    smoke: mark a test as part of the main smoke test
    standalone: mark a test that deploys its own Nessus instance.
    target_performance: mark a test as part of target performance suite.
    upload: mark a test that deals with file uploads.
    ie: mark a test to be run on internet explorer.
    license_change: mark a test as part of the licence changes.
    disable_logout: mark a test with disabled logout
    grid_only: mark a test as part of grid test only
    skip: mark a test to skip test
    update: mark a test to update
    advanced_settings: mark a test for advance settings tests
    scanner: mark a test for scanner tests
    asd: mark a test for Attach Surface Discovery tests
    linux_only: mark a test for linux os only
    feed_channel_update_home: mark tests that updates feed channel home
    feed_channel_update_manager: mark tests that updates feed channel manager
    feed_channel_update_pro: mark tests that updates feed channel pro
    managed_channel_update: mark tests that managed channel update
    nessus_engine: Test related to Nessus Engine functional area
    nessus_mat: MAT test for Nessus
    nessus_version: mark for different versions of nessus
    nessus_pro_upgrade_downgrade: mark for upgrade/downgrade tests for nessus pro.
    cluster_manager: mark for a cluster manager
    flaky_test : mark for flaky tests.
    browser_file_download: mark for downloading a file from the browser.
    real_agent: mark for using a real agent.
    skip_centos7: tests to skip for centos7.
    skip_ubuntu: tests to skip for ubuntu.
    skip_oraclelinux8: tests to skip for OL8
    skip_suse: tests to skip for suse


    # Nessus Product Markers
    nessus_legacy: mark a test that is a known Nessus legacy test.
    nessus_pro: mark a test that should only run against a Nessus Pro.
    nessus_expert: mark a test that should only run against a Nessus Expert.
    nessus_manager: mark a test that should only run against a Nessus Manager.
    sensor_manager: mark a test that should only run against a Sensor Manager.
    nessus_cli: mark a test that is a known Nessus CLI test.
    nessus_nasl: mark a test that is a known Nessus NASL test.
    nessus_legacy: mark a test that is a known Nessus legacy test.
    nessus_home: mark a test that is a known Nessus Home/Essentials test. TODO: deprecate this marker in favor of nessus_essentials
    nessus_essentials: mark a test that is a known Nessus Essentials test.
    nessus_essentials_plus: mark a test that is a known Nessus Essentials Plus test.
    nessus_agent: mark a test that is a known Nessus Agent test.
    sensor_proxy: mark tests for sensor proxy
    incompatible: mark the test that are not compatible for labvc hosts.
    sensor_proxy: mark tests for sensor proxy.
    skip_nessustc: mark a test that is excluded for Tcore+Nessus OS
    offline_mode: mark tests for Nessus offline mode


    # Nessus Engine Markers
    compile_plugins: mark a test that has to do with compiling plugins


    # Test Run Type
    serial: mark a test that runs in a serial manner.
    parallel: mark a test that runs in a parallel manner.
    unittest: mark a test that is a known unit test.
    sanity: mark tests that should be run for catium sanity build
    skip_acceptance: skip this test when running the Acceptance test suite (speed/usefulness tradeoff)
